name: Weep OpenLink Exploit Test

on:
  push:
    branches: [ main ]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Make fake open executable
        run: chmod +x fakebin/open

      - name: Prepend fakebin to PATH and run PoC
        run: |
          export PATH="${GITHUB_WORKSPACE}/fakebin:$PATH"
          go run main.go
          ls -l /tmp/pwned || echo "/tmp/pwned not found"
